"""
Detection signal functions for Provenance Guard.

Signal 1: LLM Classifier (Groq) — semantic/holistic judgment.
Signal 2 (stylometric heuristics) is added in Milestone 4.
"""

import os
import json

GROQ_MODEL = "llama-3.3-70b-versatile"

_client = None


def _get_client():
    global _client
    if _client is None:
        from groq import Groq  # imported lazily so this module still loads
                                 # for local testing even if groq isn't installed
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise RuntimeError(
                "GROQ_API_KEY is not set. Add it to your .env file."
            )
        _client = Groq(api_key=api_key)
    return _client


LLM_PROMPT = """You are analyzing a piece of writing to judge whether it was
most likely written by a human or generated by an AI language model.

Consider semantic coherence, tone, specificity of detail, and overall voice.

Respond with ONLY a JSON object in this exact format, no other text:
{{"ai_likelihood": <float between 0 and 1>, "reasoning": "<one sentence>"}}

A score near 0 means you believe this is confidently human-written.
A score near 1 means you believe this is confidently AI-generated.
A score near 0.5 means you are genuinely unsure.

Text to analyze:
---
{text}
---
"""


def get_llm_score(text: str) -> dict:
    """
    Calls Groq to get a semantic AI-likelihood judgment.

    Returns a dict: {"score": float 0-1, "reasoning": str}

    Raises RuntimeError if the API key is missing or the call fails —
    callers should handle that explicitly rather than silently guessing.
    """
    client = _get_client()

    response = client.chat.completions.create(
        model=GROQ_MODEL,
        messages=[
            {"role": "user", "content": LLM_PROMPT.format(text=text)}
        ],
        temperature=0.0,
        max_tokens=150,
    )

    raw = response.choices[0].message.content.strip()

    try:
        parsed = json.loads(raw)
        score = float(parsed["ai_likelihood"])
        score = max(0.0, min(1.0, score))  # clamp defensively
        return {"score": score, "reasoning": parsed.get("reasoning", "")}
    except (json.JSONDecodeError, KeyError, ValueError) as e:
        raise RuntimeError(f"Could not parse Groq response as expected JSON: {raw}") from e


# ---------------------------------------------------------------------------
# DEV FALLBACK — for local testing without a live Groq key.
#
# This is NOT a real detection signal. It exists only so the rest of the
# pipeline (endpoint wiring, audit logging, etc.) can be built and tested
# before a real GROQ_API_KEY is available. It is clearly separated from
# get_llm_score() above and must not be mistaken for real model output.
# ---------------------------------------------------------------------------

def get_llm_score_dev_fallback(text: str) -> dict:
    """
    Deterministic, rule-of-thumb stand-in for get_llm_score(), used only
    when GROQ_API_KEY is not configured. Flags a handful of surface phrases
    commonly associated with AI-generated text. This is intentionally crude —
    it is a placeholder for wiring/testing, not a real classifier.
    """
    ai_markers = [
        "it is important to note", "furthermore", "in conclusion",
        "delve into", "as an ai", "paradigm shift", "stakeholders",
        "it is essential", "in today's world",
    ]
    lowered = text.lower()
    hits = sum(1 for marker in ai_markers if marker in lowered)
    score = min(1.0, 0.15 + hits * 0.2)
    return {
        "score": score,
        "reasoning": f"[DEV FALLBACK — not a real model call] {hits} surface marker(s) found"
    }


# ---------------------------------------------------------------------------
# Signal 2: Stylometric heuristics (pure Python, no external libraries)
# ---------------------------------------------------------------------------

import re
import statistics


def _split_sentences(text: str):
    # Simple sentence splitter on ., !, ? — good enough for heuristics,
    # not meant to be a real NLP sentence tokenizer.
    sentences = re.split(r'(?<=[.!?])\s+', text.strip())
    return [s for s in sentences if s.strip()]


def _sentence_length_variance_score(text: str) -> float:
    """
    Higher score = more uniform sentence lengths = more AI-like.
    Measures variance in word-count per sentence, then inverts and
    normalizes so LOW variance (uniform) maps to a HIGH score.
    """
    sentences = _split_sentences(text)
    lengths = [len(s.split()) for s in sentences]

    if len(lengths) < 2:
        # Not enough sentences to measure variance meaningfully — return a
        # neutral midpoint rather than a misleadingly confident number.
        return 0.5

    variance = statistics.pvariance(lengths)
    mean_len = statistics.mean(lengths)
    # Coefficient of variation: variance relative to the mean sentence length,
    # so a 20-word vs 10-word swing doesn't get treated the same regardless
    # of whether sentences are typically short or long.
    cv = (variance ** 0.5) / mean_len if mean_len > 0 else 0

    # Low CV (uniform lengths) -> high AI-likeness score.
    # Empirically, human writing often has CV > 0.5; AI text is often < 0.3.
    # Map CV of 0 -> score 1.0, CV of 1.0+ -> score 0.0
    score = max(0.0, min(1.0, 1.0 - cv))
    return score


def _type_token_ratio_score(text: str) -> float:
    """
    Higher score = lower vocabulary diversity = more AI-like.
    Type-token ratio (TTR) = unique words / total words.
    Note: TTR naturally drops as text gets longer, regardless of authorship,
    so this is most meaningful on short-to-medium length submissions.
    """
    words = re.findall(r"[a-zA-Z']+", text.lower())
    if len(words) < 5:
        return 0.5  # too little text to measure vocabulary diversity

    ttr = len(set(words)) / len(words)
    # Lower TTR (less diverse vocabulary) -> higher AI-likeness score.
    # Invert: TTR of 1.0 (all unique) -> score 0.0, TTR of 0.4 or below -> score close to 1.0
    score = max(0.0, min(1.0, 1.0 - (ttr - 0.4) / 0.6))
    return score


def _punctuation_density_score(text: str) -> float:
    """
    Higher score = higher density of standard punctuation (. , ; :) =
    more AI-like, on the theory that AI text tends to punctuate
    consistently and "correctly," while human writing is often looser
    (run-ons, missing commas, dashes used instead of proper punctuation).

    Uses direct linear scaling against an expected density range rather
    than a "typical band" — an earlier banded version compressed nearly
    all real text into the same score regardless of direction, which
    hid the signal instead of revealing it.
    """
    if len(text) == 0:
        return 0.5

    standard_punct = len(re.findall(r'[.,;:]', text))
    density = standard_punct / len(text)

    # Linear scale: 0.0 density -> score 0.0, 0.06+ density -> score 1.0.
    # 0.06 chosen as a rough upper bound for heavily-punctuated prose;
    # this is a heuristic starting point, not a validated threshold.
    score = min(1.0, density / 0.06)
    return score


def get_stylometric_score(text: str) -> dict:
    """
    Combines three stylometric sub-signals into a single structural
    AI-likelihood score between 0 and 1.

    Returns a dict: {"score": float 0-1, "components": {...}}
    """
    sentence_score = _sentence_length_variance_score(text)
    ttr_score = _type_token_ratio_score(text)
    punct_score = _punctuation_density_score(text)

    combined = statistics.mean([sentence_score, ttr_score, punct_score])

    return {
        "score": combined,
        "components": {
            "sentence_length_variance_score": round(sentence_score, 3),
            "type_token_ratio_score": round(ttr_score, 3),
            "punctuation_density_score": round(punct_score, 3),
        }
    }


def combine_signals(llm_score: float, stylometric_score: float) -> dict:
    """
    Combines the two signal scores into a single confidence score, per the
    approach documented in planning.md:

    combined = (0.6 * llm_score) + (0.4 * stylometric_score)

    Exception: if the two signals disagree by more than 0.35, the combined
    score is pulled toward 0.5 instead of averaged normally. Large
    disagreement between a semantic judgment and a structural judgment is
    itself a sign the system doesn't confidently know what it's looking at,
    and averaging it away would hide that instead of surfacing it.

    Returns a dict: {"confidence": float, "attribution": str, "disagreement": bool}
    """
    disagreement = abs(llm_score - stylometric_score) > 0.35

    if disagreement:
        weighted = (0.6 * llm_score) + (0.4 * stylometric_score)
        # Pull toward 0.5, but don't fully discard the weighted signal —
        # split the difference between the weighted score and neutral.
        confidence = (weighted + 0.5) / 2
    else:
        confidence = (0.6 * llm_score) + (0.4 * stylometric_score)

    confidence = max(0.0, min(1.0, confidence))

    if confidence >= 0.65:
        attribution = "likely_ai"
    elif confidence <= 0.35:
        attribution = "likely_human"
    else:
        attribution = "uncertain"

    return {
        "confidence": round(confidence, 3),
        "attribution": attribution,
        "disagreement": disagreement,
    }